name: Convert a video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

      video_id:
        description: 'YouTube video Id'
        required: true
        type: string

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract 7-Zip (7z.tar.xz)
        run: |
          tar -xf 7z.tar.xz
          chmod +x ./7zz

      - name: Use 7zz to extract convert.zip
        run: |
          ./7zz x convert.zip.001 -p'${{ secrets.MASTER_KEY }}' -y

      - name: Decrypt cookies file
        run: |
          openssl enc -d -aes-256-cbc -pbkdf2 -in cookies.enc -out cookies.txt -pass pass:"${{ secrets.COOKIE_KEY }}"

      - name: Run convert.jar file
        run: |
          java -jar convert.jar
