name: Run search.jar

on:
  workflow_dispatch:

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout just search.jar
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            search.jar

      - name: Setup Java JRE 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          java-package: 'jre'

      - name: Run search.jar
        run: java -jar search.jar
